bitwarden/workflow-linter

.github/PULL_REQUEST_TEMPLATE.md, .github/renovate.json, .github/workflows/ci.yml, .github/workflows/scan.yml
Internal change.
Found a few small wins.
- 🎨 (`:art:`) …
=> Repo tuning

.github/renovate.json
https://bitwarden.atlassian.net/browse/BRE-177
Add a `version:` label to Renovate PRs. …
=> [BRE-177] Add version label to renovate PRs

.github/CODEOWNERS
- [Card](https://bitwarden.atlassian.net/browse/BRE-101)
Prepare CODEOWNERS for CI/CD partnership Phase 2:
- Update team from `dept-devops` to `dept-bre`.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for …
=> [BRE-101] Update CODEOWNERS for CI/CD Partnership Phase 2

src/bitwarden_workflow_linter/actions.py, src/bitwarden_workflow_linter/cli.py, src/bitwarden_workflow_linter/lint.py, src/bitwarden_workflow_linter/load.py, src/bitwarden_workflow_linter/rule.py, src/bitwarden_workflow_linter/utils.py
https://bitwarden.atlassian.net/browse/BRE-410
- PR to test CD worklfow
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit …
=> [BRE-139] - Clean Up Extra Spaces to Test CD Workflow

.github/workflows/cd.yml, src/bitwarden_workflow_linter/rules/job_environment_prefix.py, src/bitwarden_workflow_linter/rules/name_capitalized.py, src/bitwarden_workflow_linter/rules/name_exists.py, src/bitwarden_workflow_linter/rules/pinned_job_runner.py, src/bitwarden_workflow_linter/rules/step_approved.py, src/bitwarden_workflow_linter/rules/step_pinned.py, src/bitwarden_workflow_linter/rules/underscore_outputs.py
https://bitwarden.atlassian.net/browse/BRE-410
- Fix the bug is Release version output …
=> [BRE-139] - Revert to Using Push Trigger, Fix bug

.github/workflows/cd.yml, src/bitwarden_workflow_linter/models/job.py, src/bitwarden_workflow_linter/models/step.py
https://bitwarden.atlassian.net/browse/BRE-410
- Fix the bug in release job in CD workflow" …
=> [BRE-139] - Fix Release Bug

src/bitwarden_workflow_linter/default_settings.yaml, src/bitwarden_workflow_linter/lint.py, src/bitwarden_workflow_linter/rules/job_environment_prefix.py, src/bitwarden_workflow_linter/rules/step_approved.py, src/bitwarden_workflow_linter/rules/step_pinned.py, src/bitwarden_workflow_linter/rules/underscore_outputs.py, tests/rules/test_step_pinned.py, tests/rules/test_underscore_output.py
https://bitwarden.atlassian.net/browse/BRE-443
- FIX: unwanted files in workflow dir, allowed env vars to exist as is, underscore output finds only print the first one …
=> [BRE-410] - More Bug Fixes

Taskfile.yml, settings.yaml, src/bitwarden_workflow_linter/default_actions.json, src/bitwarden_workflow_linter/default_settings.yaml, src/bitwarden_workflow_linter/rules/step_approved.py, tests/fixtures/test.yml
https://bitwarden.atlassian.net/browse/BRE-443
- Approved action rule is activated …
=> [BRE-443] - Update Workflow Linter - Activate Approved Actions

src/bitwarden_workflow_linter/default_actions.json
Update the approved actions list to include the `nuget/setup-nuget` action.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially …
=> Add nuget/setup-nuget action

.github/workflows/cd.yml, .github/workflows/enforce-labels.yml
This PR updates the CD workflow to use our GitHub app to push a new version to `main`. …
=> Use GitHub App token

src/bitwarden_workflow_linter/default_actions.json
- [Slack thread](https://bitwarden.slack.com/archives/C024Z7LQNLB/p1736356226737039)
This PR adds the `actions/setup-go` action to the approved list of actions. …
=> Add actions/setup-go action to list of approved actions

.github/workflows/cd.yml
https://bitwarden.atlassian.net/browse/BRE-543
Run CD workflow on PR merged to `main` to prevent running in a loop. Remove checks for an actor in every job.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) …
=> [BRE-534] Update the CD workflow to not run in a loop

.github/workflows/cd.yml, .github/workflows/enforce-labels.yml
https://bitwarden.atlassian.net/browse/BRE-544
Skip version bump for 'skip' bump type and update enforce-labels workflow to allow `version:skip` label.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for …
=> [BRE-544] Add skip version bump type

src/bitwarden_workflow_linter/default_actions.json
Internal support given https://github.com/bitwarden/passkeys-index/actions/runs/12753155713/job/35544177357?pr=93.
Adds the Astro Actions that marketing engineering uses. …
=> Add Astro Action

src/bitwarden_workflow_linter/default_actions.json
https://bitwarden.atlassian.net/browse/SRE-1718
Actions for Fastly Compute workflows …
=> Fastly Compute actions

src/bitwarden_workflow_linter/default_actions.json
Add actions used in Secret Manager SDK to the approved actions list.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit …
=> Add actions used in Secret Manager SDK to the approved actions list

src/bitwarden_workflow_linter/__about__.py
This PR reverts the v1 version bump, and changes the version to the right number after the discussion on Slack. The 1.0 release (cd pipeline) was cancelled, to not release it to the GitHub and pypi.
- 🤔 …
=> Change the version to 0.7.0

src/bitwarden_workflow_linter/default_actions.json
https://bitwarden.atlassian.net/browse/PM-17331
Updating the docker/build-push-action from renovate.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue …
=> Updated docker/build-push-action to 6.12.0

src/bitwarden_workflow_linter/default_actions.json
https://bitwarden.atlassian.net/browse/PM-17331
Updating the actions/upload-artifact from renovate.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue …
=> Updated actions/upload-artifact to 4.6.0

src/bitwarden_workflow_linter/default_actions.json
https://bitwarden.atlassian.net/browse/VULN-159
Updated codecov-action to 5.1.2, and removed outdated sonarcloud-github-action which was replaced with sonarqube-scan-action in additional PRs.
- 🤔 …
=> Update SonarQube and CodeCov action versions

.github/workflows/bwwl_operations.yml
=> bwwl operation review

.github/workflows/bwwl_operations.yml
- Fix workflow id error
- 🎨 (`:art:`) for suggestions / …
=> Fix workflow id error

README.md, RULE_ROLLOUT.md
=> Add rule rollout document

.github/workflows/bwwl_operations.yml
=> Fix condition typo

.github/workflows/bwwl_operations.yml
=> Fix app token

.github/workflows/examples/ci.yaml, .github/workflows/examples/example-references/_build.yml, .github/workflows/examples/example-references/_docker.yml, .github/workflows/examples/example-references/_test.yml, .github/workflows/examples/example-references/_version.yml, .github/workflows/examples/example.yaml, .github/workflows/examples/scan.yaml, .github/workflows/lint-examples.yml
Requiring example workflows to be linted in the gh-actions directory broke workflow runs for all repositories, do this again but in the workflow-linter repo to avoid breaking dependent workflows.
- 🤔 …
=> [BRE-632] New workflow to scan examples

.github/workflows/examples/example-references/_test.yml
https://bitwarden.atlassian.net/browse/VULN-202
Remove the check for secrets. Replace with logic to identify if the code is running in a fork.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open …
=> Remove secret check for tests

src/bitwarden_workflow_linter/default_actions.json
- [BRE-706](https://bitwarden.atlassian.net/browse/BRE-706?atlOrigin=eyJpIjoiMDBmMGFkNjdlYWJlNDBmMDgxMDRjM2RlYjE0OTAyY2UiLCJwIjoiaiJ9)
This PR removes the compromised action from our linter approved list. …
=> BRE-706 - Remove compromised action from list

.github/workflows/examples/scan.yaml, .github/workflows/scan.yml
https://bitwarden.atlassian.net/browse/VULN-226
Add correct ref/sha reference for main and PR branches, since codeql/upload-sarif doesn't handle pull_request_target properly. …
=> Fix SARIF upload branch ref/sha

src/bitwarden_workflow_linter/rules/run_actionlint.py, tests/rules/test_run_actionlint.py
=> try splitting up check_actionlint

src/bitwarden_workflow_linter/rules/run_actionlint.py
related to BRE-753
temporary fix to get bwwl working while we troubleshooting actionlint_version.json config file location to be compatible with CI
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more …
=> temporary fix for actionlint versioning

src/bitwarden_workflow_linter/rules/run_actionlint.py
related to BRE-753
PR with a version:patch label to publish the updated working binary to PyPi etc
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and …
=> add comment and version patch bump

src/bitwarden_workflow_linter/default_actions.json
Related PR: https://github.com/bitwarden/server/pull/5759
Remove action that is no longer used in any of our repos.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a …
=> Remove launchdarkly/find-code-references-in-pull-request action

.github/workflows/scan.yml
[BRE-609](https://bitwarden.atlassian.net/browse/BRE-609)
update workflows to be compliant with pull_request_target workflow linter rule ahead of changing rule log level to error …
=> BRE-609/scan-update

src/bitwarden_workflow_linter/models/job.py, src/bitwarden_workflow_linter/rules/permissions_exist.py, tests/rules/test_permissions_exist.py
[BRE-827](https://bitwarden.atlassian.net/browse/BRE-827)
Allow permissions to be set on either the workflow or all jobs
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite …
=> [BRE-827] Allow permissions to be set on all jobs or workflow level

.github/workflows/bwwl_operations.yml
[BRE-828](https://bitwarden.atlassian.net/browse/BRE-828)
Revert python version until we can fix the code to work with 3.13
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not …
=> [BRE-828] Reverting to 3.12 for install

README.md, settings.yaml, src/bitwarden_workflow_linter/default_settings.yaml
[BRE-609](https://bitwarden.atlassian.net/browse/BRE-609)
now that all pre-req work has been done - this PR is to be merged on Monday May 19th in the morning 
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) …
=> BRE-609/flip-pr-target-rule-to-error

settings.yaml, src/bitwarden_workflow_linter/default_settings.yaml
- https://bitwarden.atlassian.net/browse/BRE-727
- Flips permission exist rule to `error` …
=> [BRE-727] - Activate Permission Rule Error

.github/workflows/bwwl_operations.yml
[BRE-831](https://bitwarden.atlassian.net/browse/BRE-831)
Adds the action name to the auto generated PR title
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a …
=> BRE-831 Adding action name to BWWL Operations PR

src/bitwarden_workflow_linter/rules/check_pr_target.py, tests/rules/test_check_pr_target.py
[BRE-831](https://bitwarden.atlassian.net/browse/BRE-831)
Updating error wording for repos with custom default branches
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite …
=> [BRE-831] Updating error wording for repos with custom default branches

.github/workflows/bwwl_operations.yml
In the workflow of adding new actions, it relies on an engineer contacting appsec in an outside channel. By having the engineer run the workflow action themselves, it will trigger a PR creation for appsec to review and notify them directly. However, appsec wants to capture an artifact for the additional action as well as displaying the actor that initiated the request in case questions arise. The artifact can take the form of a JIRA ticket, a URL, a business reason, etc.
- Communicated to DevOps any …
=> Update workflow action to include artifact and actor
